on:
  schedule:
    - cron: '30 11 * * *'

name: Create nightly build and upload binaries

jobs:
  build-linux:
    name: Build Linux All
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: 'slackhq/nebula'

      - name: Build
        run: |
          BUILD_NUMBER="v0.0.0-nightly$(date +%Y%m%d)"
          REMOTE="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git tag "$BUILD_NUMBER"
          git push "$REMOTE" "$BUILD_NUMBER"
