on:
  schedule:
    - cron: '0 3 * * *'

name: Tag nightly

jobs:
  tag-nightly:
    name: Tag nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: 'slackhq/nebula'
          fetch-depth: 0

      - name: Build
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.DEPLOY_KEY }}"

          REMOTE="git@github.com:${GITHUB_REPOSITORY}.git"

          git fetch --tags
          LATEST="$(git describe --tags --long --match 'v[0-9]*' --exclude '*-*' | cut -d- -f 1)"
          if [ -z "$LATEST" ]
          then
            echo "failed to find latest tag" >&2
            exit 1
          fi

          MAJOR_MINOR="$(echo "$LATEST" | cut -d. -f 1-2)"
          PATCH="$(echo "$LATEST" | cut -d. -f 3)"
          NEXT="$MAJOR_MINOR.$((PATCH + 1))"

          PUSH_OUT="$(git push -f "$REMOTE" "master:nightly-$NEXT")"
          if [ "$PUSH_OUT" = "Everything up-to-date" ]
          then
            exit 0
          fi

          BUILD_NUMBER="$NEXT-nightly$(date +%Y%m%d)"
          git tag "$BUILD_NUMBER"
          git push "$REMOTE" "$BUILD_NUMBER"
