on:
  schedule:
    - cron: '55 11 * * *'

name: Create nightly build and upload binaries

jobs:
  tag-nightly:
    name: Tag nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: 'slackhq/nebula'
          fetch-depth: 0

      - name: Build
        run: |
          mkdir -p ~/.ssh
          chmod 600 ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" >~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

          BUILD_NUMBER="v0.0.0-nightly$(date +%Y%m%d)"
          REMOTE="git@github.com:${GITHUB_REPOSITORY}.git"
          git tag "$BUILD_NUMBER"
          git push "$REMOTE" "$BUILD_NUMBER"
